# Generated by Django 4.2.14 on 2025-07-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('connector_id', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='Unknown', max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_tag', models.CharField(blank=True, max_length=50)),
                ('start_wh', models.FloatField(blank=True, null=True)),
                ('latest_wh', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csms.chargepoint')),
            ],
        ),
    ]
