# Generated by Django 4.2.14 on 2025-07-09 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
