# Generated by Django 4.2.14 on 2025-07-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0003_remove_chargepoint_owner_alter_transaction_cp_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='ws_secret',
        ),
        migrations.AddField(
            model_name='tenant',
            name='ws_key',
            field=models.CharField(default='', help_text='Per-tenant secret shown in the WebSocket URL.', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
