# Generated by Django 4.2.14 on 2025-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0004_remove_tenant_created_at_remove_tenant_ws_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='fw_version',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='model',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='vendor',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
