# Generated by Django 4.2.14 on 2025-07-11 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0005_chargepoint_fw_version_chargepoint_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmd_queue', to='csms.chargepoint')),
            ],
            options={
                'indexes': [models.Index(fields=['cp', 'done_at', 'created'], name='csms_cpcomm_cp_id_e86e11_idx')],
            },
        ),
    ]
