# Generated by Django 4.2.14 on 2025-07-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0006_cpcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='price_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
