# Generated by Django 4.2.14 on 2025-07-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0007_chargepoint_location_chargepoint_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price_h_at_start',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_kwh_at_start',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
