# Generated by Django 4.2.14 on 2025-07-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0008_transaction_price_h_at_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_h_at_start',
            new_name='price_hour_at_start',
        ),
    ]
