# Generated by Django 4.2.14 on 2025-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0009_rename_price_h_at_start_transaction_price_hour_at_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
