# Generated by Django 4.2.14 on 2025-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0010_chargepoint_lat_chargepoint_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal user'), ('super_admin', 'Super Admin')], default='user', max_length=12),
        ),
    ]
