# Generated by Django 4.2.14 on 2025-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
