# Generated by Django 4.2.14 on 2025-08-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0012_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='access_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('limited', 'Limited'), ('private', 'Private')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='max_power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='plug_type',
            field=models.CharField(blank=True, choices=[('type2', 'Type 2'), ('eu', 'EU Schuko'), ('uk', 'UK 3-pin'), ('swiss', 'Swiss T13/T23'), ('ccs2', 'CCS Combo 2'), ('chademo', 'CHAdeMO')], max_length=20, null=True),
        ),
    ]
