# Generated by Django 4.2.14 on 2025-08-31 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0013_chargepoint_access_type_chargepoint_max_power_kw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePointUserPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prices', to='csms.chargepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cp', 'user')},
            },
        ),
    ]
